## EVALUACIÓN SPRINT 1 - MODULO 2: NUMPY 

#### Ejercicios de NumPy

In [4]:
# 1. Importa la librería de NumPy

import numpy as np

In [2]:
# 2. Crea un array de 1 dimension y 10 elementos.
array_dimension1 = np.arange(10)
array_dimension1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array_vacio_d1 = np.empty_like(array_dimension1, dtype = object)
array_vacio_d1

array([None, None, None, None, None, None, None, None, None, None],
      dtype=object)

In [5]:
# 3. Reemplaza todos los números impares por el valor "impar" y los pares por "par". 
# Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

contador = 0

for elemento in array_dimension1:
    if elemento % 2 == 0:
        array_vacio_d1[contador] = "par"
        contador += 1
    else:
        array_vacio_d1[contador] = "impar"
        contador += 1

array_vacio_d1

array(['par', 'impar', 'par', 'impar', 'par', 'impar', 'par', 'impar',
       'par', 'impar'], dtype=object)

In [6]:
#4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.
   
array_nueva_ndim = np.reshape(array_vacio_d1, (2,5))
array_nueva_ndim

array([['par', 'impar', 'par', 'impar', 'par'],
       ['impar', 'par', 'impar', 'par', 'impar']], dtype=object)

In [11]:
# 5. Extrae los elementos comunes de los siguientes arrays

array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [55]:
#Para exraer los elementos comunes de estos dos arrays utilizamos el método np.intersect1d(), que nos permite obtener los elementos comunes.
#El resultado es un array con los valores únicos de la intersección de ambos array.
np.intersect1d(array1,array2)

array([2, 4])

In [56]:
#  6. Extraed los elementos que están en el array1 pero no en el array2.

# Para solucionar este ejercicio necesitamos utilizar el método setdiff1d(). 
# El orden aquí es importante y por ello ponemos en primera posición el array del que queremos sacar los elementos únicos en comparación con el otro

np.setdiff1d(array1, array2)


array([1, 3, 5, 6])

In [65]:
# 7. Extraed las posiciones donde tengamos elementos que sean iguales.

#De nuevo, como tenemos que sacar los elementos iguales en ambos array, aplicamos el mét intersect1d().
# A este le añadimos el parámetro return_indices = True, que nos permite obtener dos array más en el resultado, 
# con los índices correspondientes a las posiciones de los elementos comunes en el array

np.intersect1d(array1, array2, return_indices=True)

(array([2, 4]), array([1, 5]), array([1, 5]))

In [67]:
#8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. 

array_nuevo = np.random.randint(0,50, (3,5))
array_nuevo

array([[ 0, 36, 23, 42, 45],
       [16, 39, 18, 38, 36],
       [32, 29, 16, 30, 26]])

In [71]:
# Una vez creado, extraemos los valores que sean menores que 10 y mayores que 40.

array_nuevo[(array_nuevo < 10) | (array_nuevo > 40)]

array([ 0, 42, 45])

In [79]:
# 9.  Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.
 
array_decimales = np.random.uniform(low=5, high=10, size=(5,3)).round(2)
array_decimales

array([[8.39, 8.84, 9.78],
       [9.82, 5.52, 6.38],
       [8.55, 9.68, 9.21],
       [6.64, 5.2 , 6.31],
       [9.15, 7.51, 9.29]])

In [80]:
# 10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20

array_dim3 = np.random.randint(1,20, (2,4,7))
array_dim3

array([[[13,  6,  7,  7, 16,  4, 15],
        [ 6, 11, 15,  8, 17,  3,  7],
        [ 7,  5,  8, 11,  1, 10,  9],
        [18, 13, 16,  6,  8, 16,  5]],

       [[ 1,  9,  2,  6, 10,  5,  8],
        [ 7, 12, 12,  2,  5,  5, 19],
        [11,  2,  3,  3,  1, 19,  5],
        [18, 14,  3, 16,  8, 19,  1]]])

In [84]:
# Transponemos el array para que tenga 4 matrices, 7 filas y 2 columnas.
array_dim3_transpuesto = np.transpose (array_dim3, (1, 2,0))
array_dim3_transpuesto

array([[[13,  1],
        [ 6,  9],
        [ 7,  2],
        [ 7,  6],
        [16, 10],
        [ 4,  5],
        [15,  8]],

       [[ 6,  7],
        [11, 12],
        [15, 12],
        [ 8,  2],
        [17,  5],
        [ 3,  5],
        [ 7, 19]],

       [[ 7, 11],
        [ 5,  2],
        [ 8,  3],
        [11,  3],
        [ 1,  1],
        [10, 19],
        [ 9,  5]],

       [[18, 18],
        [13, 14],
        [16,  3],
        [ 6, 16],
        [ 8,  8],
        [16, 19],
        [ 5,  1]]])